# Site settings
title: Example Jekyll Site Hosted On Github
email: no-reply@gmail.com
description: A simple Jekyll blog hosted on Github.
baseurl: "/example-jekyll-github"
avatar: "//media.licdn.com/mpr/mpr/shrinknp_400_400/p/5/005/008/330/20c0f7c.jpg" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Sarn Phamornsuwana" # Set default author name
      categories: "cats"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
